name: testing.yml
on:
  pull_request:
    branches: [main]
jobs:
    test-unit:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - run: npm ci
        - run: npm i -g jest
        - run: jest -b "test/**/*.test.js" --collectCoverage

    test-integration:
      runs-on: ubuntu-latest
      needs: test-unit
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - run: npm ci
        - run: npm i -g jest
        - run: jest -b "test/**/*.test-tegration.js"
